modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory (26 is current forge version)
issueTrackerURL="https://github.com/noobanidus/w2w/issues" #optional
[[mods]] #mandatory
modId="w2w" #mandatory
version="${file.jarVersion}" #mandatory
displayName="w2w" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/waystones2waypoints" #optional
authors="Noobanidus"
description='''
Adds waypoints whenever you find Waystones.
'''
[[dependencies.w2w]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.w2w]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
